import React from "react"
import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"

import { useHello } from "../utils/hello"
import styles from "../styles/Home.module.css"

const isError = (error: unknown): error is Error => error instanceof Error

const HelloPage: NextPage = () => {
  const { data, error } = useHello()

  return (
    <div className={styles.container}>
      <Head>
        <title>SITH Front-End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello, welcome to the test page</h1>

        <p className={styles.description}>
          Greeting from the Backend:{" "}
          <code className={styles.code}>
            {data ? data.hello : isError(error) ? error.message : "loading..."}
          </code>
        </p>

        <Link href="/">
          <a className={styles.card}>Home</a>
        </Link>
      </main>
    </div>
  )
}

export default HelloPage
