name: Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image for app
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.dev
          push: false
          tags: nextjs:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
